import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:image_picker/image_picker.dart';
import '../../../../core/utils/image_helper.dart';
import '../../../../core/di/injection_container.dart';
import '../../domain/entities/car_entity.dart';
import '../bloc/car_bloc.dart';
import '../bloc/car_event.dart';
import '../bloc/car_state.dart';
import '../../../auth/presentation/bloc/auth_bloc.dart';
import '../../../auth/presentation/bloc/auth_state.dart';
import '../../../../l10n/generated/app_localizations.dart';

class AddCarPage extends StatefulWidget {
  const AddCarPage({super.key});

  @override
  State<AddCarPage> createState() => _AddCarPageState();
}

class _AddCarPageState extends State<AddCarPage> {
  final _formKey = GlobalKey<FormState>();
  final _makeController = TextEditingController();
  final _modelController = TextEditingController();
  final _yearController = TextEditingController();
  final _priceController = TextEditingController();
  final _mileageController = TextEditingController();
  final _locationController = TextEditingController();
  final _phoneController = TextEditingController();
  final _descriptionController = TextEditingController();
  String _condition = 'Used';
  String _location = 'Gaza City';
  
  final List<File> _selectedImages = [];
  final ImagePicker _picker = ImagePicker();

  @override
  void dispose() {
    _makeController.dispose();
    _modelController.dispose();
    _yearController.dispose();
    _priceController.dispose();
    _mileageController.dispose();
    _locationController.dispose();
    _phoneController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  Future<void> _pickImage(ImageSource source) async {
    final XFile? image = await _picker.pickImage(source: source);
    if (image != null) {
      final compressedImage = await ImageHelper.compressImage(File(image.path));
      if (compressedImage != null) {
        setState(() {
          _selectedImages.add(compressedImage);
        });
      }
    }
  }

  void _onSavePressed(BuildContext context) {
    if (_formKey.currentState!.validate()) {
      if (_selectedImages.isEmpty) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(AppLocalizations.of(context)!.uploadImages)),
        );
        return;
      }
      // Trigger image upload first
      context.read<CarBloc>().add(UploadCarImagesEvent(_selectedImages));
    }
  }

  void _submitCar(BuildContext context, List<String> imageUrls) {
    final currentUser = context.read<AuthBloc>().state;
    String sellerId = '';
    if (currentUser is AuthAuthenticated) {
      sellerId = currentUser.user.uid;
    }

    final car = CarEntity(
      id: '', // Generated by Firestore
      sellerId: sellerId,
      sellerPhone: _phoneController.text,
      make: _makeController.text,
      model: _modelController.text,
      year: int.parse(_yearController.text),
      price: double.parse(_priceController.text),
      mileage: int.parse(_mileageController.text),
      condition: _condition,
      location: _location,
      description: _descriptionController.text,
      images: imageUrls,
      status: 'active',
      createdAt: DateTime.now(),
    );

    context.read<CarBloc>().add(AddCarEvent(car));
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    return BlocProvider(
      create: (context) => sl<CarBloc>(),
      child: Scaffold(
        appBar: AppBar(title: Text(l10n.addCar)),
        body: BlocConsumer<CarBloc, CarState>(
          listener: (context, state) {
            if (state is CarOperationSuccess) {
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(content: Text(l10n.carAddedSuccess)),
              );
              context.pop();
            } else if (state is CarError) {
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(content: Text(state.message)),
              );
            } else if (state is CarImagesUploaded) {
               // Images uploaded, now submit car
               _submitCar(context, state.imageUrls);
            }
          },
          builder: (context, state) {
            if (state is CarLoading) {
              return const Center(child: CircularProgressIndicator());
            }
            return SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Form(
                key: _formKey,
                child: Column(
                  children: [
                    _buildImagePicker(l10n),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _makeController,
                      decoration: InputDecoration(labelText: l10n.make),
                      validator: (value) =>
                          value!.isEmpty ? l10n.requiredField : null,
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _modelController,
                      decoration: InputDecoration(labelText: l10n.model),
                      validator: (value) =>
                          value!.isEmpty ? l10n.requiredField : null,
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _yearController,
                      decoration: InputDecoration(labelText: l10n.year),
                      keyboardType: TextInputType.number,
                      validator: (value) =>
                          value!.isEmpty ? l10n.requiredField : null,
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _priceController,
                      decoration: InputDecoration(labelText: l10n.price),
                      keyboardType: TextInputType.number,
                      validator: (value) =>
                          value!.isEmpty ? l10n.requiredField : null,
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _mileageController,
                      decoration: InputDecoration(labelText: l10n.mileage),
                      keyboardType: TextInputType.number,
                      validator: (value) =>
                          value!.isEmpty ? l10n.requiredField : null,
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _phoneController,
                      decoration: InputDecoration(
                        labelText: l10n.phone,
                        hintText: '+970 XXX XXX XXX',
                        prefixIcon: const Icon(Icons.phone),
                      ),
                      keyboardType: TextInputType.phone,
                      validator: (value) =>
                          value!.isEmpty ? l10n.requiredField : null,
                    ),
                    const SizedBox(height: 16),
                    DropdownButtonFormField<String>(
                      initialValue: _condition,
                      decoration: InputDecoration(labelText: l10n.condition),
                      items: [
                        DropdownMenuItem(value: 'New', child: Text(l10n.newCondition)),
                        DropdownMenuItem(value: 'Used', child: Text(l10n.usedCondition)),
                        DropdownMenuItem(value: 'Damaged', child: Text(l10n.damagedCondition)),
                      ],
                      onChanged: (value) {
                        setState(() {
                          _condition = value!;
                        });
                      },
                    ),
                    const SizedBox(height: 16),
                    DropdownButtonFormField<String>(
                      initialValue: _location,
                      decoration: InputDecoration(labelText: l10n.location),
                      items: ['Gaza City', 'Khan Yunis', 'Rafah', 'Deir al-Balah', 'Jabalia']
                          .map((location) => DropdownMenuItem(
                                value: location,
                                child: Text(location),
                              ))
                          .toList(),
                      onChanged: (value) {
                        setState(() {
                          _location = value!;
                        });
                      },
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _descriptionController,
                      decoration: InputDecoration(labelText: l10n.description),
                      maxLines: 3,
                    ),
                    const SizedBox(height: 24),
                    ElevatedButton(
                      onPressed: () => _onSavePressed(context),
                      child: Text(l10n.addCar),
                    ),
                  ],
                ),
              ),
            );
          },
        ),
      ),
    );
  }

  Widget _buildImagePicker(AppLocalizations l10n) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(l10n.uploadImages, style: Theme.of(context).textTheme.titleMedium),
        const SizedBox(height: 8),
        Wrap(
          spacing: 8,
          runSpacing: 8,
          children: [
            ..._selectedImages.map((file) => Stack(
                  children: [
                    Image.file(file, width: 100, height: 100, fit: BoxFit.cover),
                    Positioned(
                      right: 0,
                      top: 0,
                      child: IconButton(
                        icon: const Icon(Icons.close, color: Colors.red),
                        onPressed: () {
                          setState(() {
                            _selectedImages.remove(file);
                          });
                        },
                      ),
                    ),
                  ],
                )),
            InkWell(
              onTap: () => _showImageSourceActionSheet(context, l10n),
              child: Container(
                width: 100,
                height: 100,
                color: Colors.grey[300],
                child: const Icon(Icons.add_a_photo),
              ),
            ),
          ],
        ),
      ],
    );
  }

  void _showImageSourceActionSheet(BuildContext context, AppLocalizations l10n) {
    showModalBottomSheet(
      context: context,
      builder: (context) => SafeArea(
        child: Wrap(
          children: [
            ListTile(
              leading: const Icon(Icons.photo_library),
              title: Text(l10n.gallery),
              onTap: () {
                Navigator.of(context).pop();
                _pickImage(ImageSource.gallery);
              },
            ),
            ListTile(
              leading: const Icon(Icons.photo_camera),
              title: Text(l10n.camera),
              onTap: () {
                Navigator.of(context).pop();
                _pickImage(ImageSource.camera);
              },
            ),
          ],
        ),
      ),
    );
  }
}
